package com.pinup.pfm.model.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User implements java.io.Serializable {

    private String id;
    private String serverId;
    private String name;
    private java.util.Date dob;

    public User() {
    }

    public User(String id) {
        this.id = id;
    }

    public User(String id, String serverId, String name, java.util.Date dob) {
        this.id = id;
        this.serverId = serverId;
        this.name = name;
        this.dob = dob;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getServerId() {
        return serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getDob() {
        return dob;
    }

    public void setDob(java.util.Date dob) {
        this.dob = dob;
    }

}
